language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer install --no-interaction --prefer-source

script: 
  - composer test

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml

